### ISSUE TITLE
cmd `start [magnetlink]` failed to execute

### ISSUE THREAD

**Issue by jtara1** [jtara1/HorribleSubsBatchDownloader#3]
![image](https://user-images.githubusercontent.com/7478231/27459078-4f5ebc80-5761-11e7-825e-5d1e7d58a129.png)

This is an issue from another user (using deluge as torrent client). It looks like the start command sent via command line is failing. I'll test it later on windows.

**Comment by jtara1** [comment]
![image](https://user-images.githubusercontent.com/7478231/27460855-5e207e2a-576b-11e7-876b-d43b6c701878.png)

> to get this to work i added my deluge folder to windows path and changed this method.  Thanks alot man!

**Comment by oddhap** [comment]
I fixed it by using os.startfile, this should be torrent-client independent
`    def download(self):
        """Downloads every episode in self.episodes"""
        if platform.system() == 'Windows':
            cli_tool = 'start'
            wrap_marks = '"'
        else:
            cli_tool = 'xdg-open'
            wrap_marks = ''

        for episode in self.episodes:
            os.startfile(episode['magnet_url'])`
